### ISSUE TITLE
styles

### ISSUE THREAD

**Issue by angelini75** [anitagraser/QGIS-resources#5]
Hi,

I'm trying to import styles from https://github.com/anitagraser/QGIS-resources/blob/master/symbols/osm_symbols.xml with QGIS 2.0.1 (Ubuntu 14.04). I'm using the QGIS style manager and I got this error: 'An error occured during import:
Unable to understand the style file: .../osm_symbols.xml'

Could you tell me if there is any other way to do this?
It would be nice to add this information at the read.me file.

Best,
Marcos

**Comment by armandorleans** [comment]
Hi,
I have the same issue than Angelini75, the raw link is down... Do you have another link please ?
Thanks for your different posts !!

Best,
Armand.

**Comment by anitagraser** [comment]
see https://raw.githubusercontent.com/anitagraser/QGIS-resources/master/qgis1.8/symbols/osm_symbols.xml
