### ISSUE TITLE
Problem loading QML files

### ISSUE THREAD

**Issue by lcoandrade** [anitagraser/QGIS-resources#6]
Dear Anita,
Please, disconsider this report. I've had access to a corrupted qml file while downloading. Sorry for the inconvenience.

**Comment by anitagraser** [comment]
Which style are you using and are you using the raw download option?

**Comment by lcoandrade** [comment]
Dear Anita,
Please, disconsider this report. I've had access to a corrupted qml file while downloading. Sorry for the inconvenience.
